[package]
name = "dreadnought"
version = "0.1.0"
authors = ["blacktop <blacktop@users.noreply.github.com>"]
edition = "2018"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "100.0.1"